<?php

namespace Database\Seeders;

use App\Models\Animal;
use App\Models\SpeciesType;
use App\Models\ConservationStatus;
use Illuminate\Database\Seeder;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mammalType = SpeciesType::where('name', 'Mammal')->first();
        $birdType = SpeciesType::where('name', 'Bird')->first();
        $reptileType = SpeciesType::where('name', 'Reptile')->first();
        $fishType = SpeciesType::where('name', 'Fish')->first();
        $marineType = SpeciesType::where('name', 'Marine')->first();
        $amphibianType = SpeciesType::where('name', 'Amphibian')->first();

        $extinct = ConservationStatus::where('name', 'Least Concern')->first();
        $vulnerable = ConservationStatus::where('name', 'Vulnerable')->first();
        $endangered = ConservationStatus::where('name', 'Endangered')->first();
        $criticallyEndangered = ConservationStatus::where('name', 'Critically Endangered')->first();
        $extinctWild = ConservationStatus::where('name', 'Extinct in the Wild')->first();

        $animals = [
            // Critically Endangered
            [
                'name' => 'Sumatran Orangutan',
                'scientific_name' => 'Pongo abelii',
                'common_name' => 'Orangutan',
                'description' => 'Our closest living relative with 97% shared DNA. Highly intelligent red apes found primarily in Sumatra rainforests.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Fruits, leaves, insects, bird eggs',
                'estimated_population' => 6600,
                'regions' => [1],
            ],
            [
                'name' => 'Javan Rhino',
                'scientific_name' => 'Rhinoceros sondaicus',
                'common_name' => 'Javan Rhinoceros',
                'description' => 'One of the rarest mammals on Earth with fewer than 75 individuals remaining. Found only in Java.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical forests and grasslands',
                'diet' => 'Leaves, fruits, bark',
                'estimated_population' => 75,
                'regions' => [2],
            ],
            [
                'name' => 'Sumatran Tiger',
                'scientific_name' => 'Panthera tigris sumatrae',
                'common_name' => 'Tiger',
                'description' => 'The smallest tiger subspecies, critically endangered and found only in Sumatra.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Dense rainforests',
                'diet' => 'Deer, wild boar, monkeys',
                'estimated_population' => 400,
                'regions' => [1],
            ],
            [
                'name' => 'Javan Gibbon',
                'scientific_name' => 'Hylobates moloch',
                'common_name' => 'Gibbon',
                'description' => 'Endemic to Java, these small apes are known for their acrobatic swinging through trees.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Fruits, leaves, insects',
                'estimated_population' => 4000,
                'regions' => [2],
            ],
            [
                'name' => 'Proboscis Monkey',
                'scientific_name' => 'Nasalis larvatus',
                'common_name' => 'Monyet Belanda',
                'description' => 'Endemic to Borneo, famous for its large distinctive nose. Excellent swimmers.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Swamp forests, mangroves, riverine forest',
                'diet' => 'Unripe seeds, leaves, unripe fruits',
                'estimated_population' => 7000,
                'regions' => [3],
            ],
            [
                'name' => 'Javan Leopard',
                'scientific_name' => 'Panthera pardus melas',
                'common_name' => 'Leopard',
                'description' => 'Critically endangered subspecies endemic to the island of Java.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical rainforests and plantations',
                'diet' => 'Deer, wild boar, primates',
                'estimated_population' => 250,
                'regions' => [2],
            ],

            // Endangered
            [
                'name' => 'Malayan Sun Bear',
                'scientific_name' => 'Helarctos malayanus',
                'common_name' => 'Sun Bear',
                'description' => 'Small bear species with distinctive chest markings. Found in Southeast Asian forests.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Tropical forests',
                'diet' => 'Insects, honey, fruits, leaves',
                'estimated_population' => 7000,
                'regions' => [1, 3, 4],
            ],
            [
                'name' => 'Pygmy Elephant',
                'scientific_name' => 'Elephas maximus borneensis',
                'common_name' => 'Borneo Elephant',
                'description' => 'Smallest elephant subspecies endemic to Borneo. Weighs only 2,700 kg.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Leaves, fruits, bark, grasses',
                'estimated_population' => 1500,
                'regions' => [3],
            ],
            [
                'name' => 'Bornean Orangutan',
                'scientific_name' => 'Pongo pygmaeus',
                'common_name' => 'Orangutan',
                'description' => 'Found in Borneo, these apes are smaller than their Sumatran cousins.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Fruits, leaves, insects, bird eggs',
                'estimated_population' => 41000,
                'regions' => [3],
            ],
            [
                'name' => 'Babirusa',
                'scientific_name' => 'Babyrousa babyrussa',
                'common_name' => 'Pig-Deer',
                'description' => 'Unique pig-like animal endemic to Sulawesi with distinctive tusks.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Tropical forests and wetlands',
                'diet' => 'Fruits, roots, nuts, invertebrates',
                'estimated_population' => 4000,
                'regions' => [4],
            ],
            [
                'name' => 'Sulawesi Crested Macaque',
                'scientific_name' => 'Macaca nigra',
                'common_name' => 'Macaque',
                'description' => 'Endemic to Sulawesi with a distinctive crest of hair and black fur.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Fruits, seeds, leaves, insects',
                'estimated_population' => 4000,
                'regions' => [4],
            ],

            // Birds
            [
                'name' => 'Rhinoceros Hornbill',
                'scientific_name' => 'Buceros rhinoceros',
                'common_name' => 'Hornbill',
                'description' => 'Large tropical forest bird with distinctive casque on its bill.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Dense rainforests',
                'diet' => 'Fruits, insects, small animals',
                'estimated_population' => 50000,
                'regions' => [1, 3],
            ],
            [
                'name' => 'Congo Peafowl',
                'scientific_name' => 'Afropavo congensis',
                'common_name' => 'Peafowl',
                'description' => 'Incredibly rare and beautiful bird endemic to Sulawesi highlands.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical montane forests',
                'diet' => 'Seeds, insects, fruits',
                'estimated_population' => 300,
                'regions' => [4],
            ],
            [
                'name' => 'Storm\'s Stork',
                'scientific_name' => 'Ciconia stormi',
                'common_name' => 'Stork',
                'description' => 'A rare, elusive stork found in lowland forests of Southeast Asia.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Lowland and tropical forests',
                'diet' => 'Fish, frogs, crustaceans',
                'estimated_population' => 2500,
                'regions' => [1, 3],
            ],
            [
                'name' => 'White-tailed Eagle',
                'scientific_name' => 'Haliaeetus albicilla',
                'common_name' => 'Eagle',
                'description' => 'A majestic large eagle with distinctive white tail feathers.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Coastal areas, wetlands, forests',
                'diet' => 'Fish, birds, small mammals',
                'estimated_population' => 50000,
                'regions' => [1, 2, 4, 6],
            ],

            // Reptiles
            [
                'name' => 'Komodo Dragon',
                'scientific_name' => 'Varanus komodoensis',
                'common_name' => 'Dragon',
                'description' => 'Largest living lizard species, endemic to Komodo and nearby islands.',
                'species_type_id' => $reptileType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Dry forests and grasslands',
                'diet' => 'Carrion, large prey like deer and boar',
                'estimated_population' => 3000,
                'regions' => [7, 8],
            ],
            [
                'name' => 'Philippine Crocodile',
                'scientific_name' => 'Crocodylus mindorensis',
                'common_name' => 'Crocodile',
                'description' => 'Critically endangered freshwater crocodile endemic to parts of Southeast Asia.',
                'species_type_id' => $reptileType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Freshwater rivers and lakes',
                'diet' => 'Fish, frogs, small mammals',
                'estimated_population' => 250,
                'regions' => [2],
            ],
            [
                'name' => 'Reticulated Python',
                'scientific_name' => 'Malayopython reticulatus',
                'common_name' => 'Python',
                'description' => 'One of the longest snakes in the world, found in Southeast Asian forests.',
                'species_type_id' => $reptileType->id,
                'conservation_status_id' => $extinct->id,
                'habitat' => 'Tropical rainforests and wetlands',
                'diet' => 'Small mammals, birds, reptiles',
                'estimated_population' => 500000,
                'regions' => [1, 2, 3],
            ],

            // Marine
            [
                'name' => 'Hawksbill Sea Turtle',
                'scientific_name' => 'Eretmochelys imbricata',
                'common_name' => 'Sea Turtle',
                'description' => 'Critically endangered sea turtle known for beautiful shell patterns.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Coral reefs and coastal waters',
                'diet' => 'Jellyfish, sea urchins, sponges',
                'estimated_population' => 23000,
                'regions' => [6, 7, 8],
            ],
            [
                'name' => 'Dugong',
                'scientific_name' => 'Dugong dugon',
                'common_name' => 'Sea Cow',
                'description' => 'Large marine mammal that grazes on seagrass in shallow coastal waters.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Coastal seagrass beds',
                'diet' => 'Seagrass',
                'estimated_population' => 100000,
                'regions' => [1, 5, 6],
            ],
            [
                'name' => 'Vaquita',
                'scientific_name' => 'Phocoena sinus',
                'common_name' => 'Harbor Porpoise',
                'description' => 'World\'s rarest marine mammal, one of the most endangered animals.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Shallow coastal waters',
                'diet' => 'Fish, squid',
                'estimated_population' => 10,
                'regions' => [5],
            ],

            // Fish
            [
                'name' => 'Tequila Splitfin',
                'scientific_name' => 'Zoogoneticus tequila',
                'common_name' => 'Splitfin',
                'description' => 'Small fish endemic to Mexico, now primarily found in Indonesia aquariums.',
                'species_type_id' => $fishType->id,
                'conservation_status_id' => $extinctWild->id,
                'habitat' => 'Freshwater springs',
                'diet' => 'Small insects, zooplankton',
                'estimated_population' => 1000,
                'regions' => [5],
            ],

            // Amphibians
            [
                'name' => 'Javan Tree Frog',
                'scientific_name' => 'Nyctibatrachidae species',
                'common_name' => 'Tree Frog',
                'description' => 'Small tree-dwelling frog endemic to Java highlands.',
                'species_type_id' => $amphibianType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Montane tropical forests',
                'diet' => 'Small insects',
                'estimated_population' => 5000,
                'regions' => [2],
            ],
            [
                'name' => 'Sumatran Striped Rabbit',
                'scientific_name' => 'Nesolagus netscheri',
                'common_name' => 'Rabbit',
                'description' => 'Rare small rabbit endemic to Sumatra\'s rainforests.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Rainforests',
                'diet' => 'Grasses, leaves, bark',
                'estimated_population' => 900,
                'regions' => [1],
            ],
            [
                'name' => 'Tapanuli Orangutan',
                'scientific_name' => 'Pongo tapanuliensis',
                'common_name' => 'Orangutan',
                'description' => 'Most recently discovered orangutan species, found in North Sumatra.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Fruits, leaves, insects',
                'estimated_population' => 800,
                'regions' => [1],
            ],
            [
                'name' => 'Sunda Leopard Cat',
                'scientific_name' => 'Prionailurus bengalensis',
                'common_name' => 'Leopard Cat',
                'description' => 'Small wild cat found throughout Southeast Asia.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $extinct->id,
                'habitat' => 'Forests and open areas',
                'diet' => 'Small rodents, birds, insects',
                'estimated_population' => 500000,
                'regions' => [1, 2, 3, 4],
            ],
            [
                'name' => 'Rafflesia',
                'scientific_name' => 'Rafflesia arnoldii',
                'common_name' => 'Giant Flower',
                'description' => 'World\'s largest flower, endemic to Sumatra and Borneo rainforests.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Parasitic plant',
                'estimated_population' => 5000,
                'regions' => [1, 3],
            ],

            // Small Islands Fauna
            // Timor
            [
                'name' => 'Timor Monitor Lizard',
                'scientific_name' => 'Varanus timorensis',
                'common_name' => 'Monitor Lizard',
                'description' => 'Medium-sized monitor lizard endemic to Timor and nearby islands.',
                'species_type_id' => $reptileType->id,
                'conservation_status_id' => $extinct->id,
                'habitat' => 'Tropical forests and grasslands',
                'diet' => 'Small vertebrates, insects, eggs',
                'estimated_population' => 100000,
                'regions' => [9],
            ],
            [
                'name' => 'Yellow-crested Cockatoo',
                'scientific_name' => 'Cacatua sulphurea',
                'common_name' => 'Cockatoo',
                'description' => 'Critically endangered white cockatoo with yellow crest endemic to Timor region.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $criticallyEndangered->id,
                'habitat' => 'Tropical dry forests',
                'diet' => 'Seeds, nuts, fruits, insects',
                'estimated_population' => 350,
                'regions' => [9],
            ],

            // Mentawai Islands - Endemic primates
            [
                'name' => 'Mentawai Macaque',
                'scientific_name' => 'Macaca pagensis',
                'common_name' => 'Macaque',
                'description' => 'Endemic to Mentawai Islands, these monkeys are found nowhere else in the wild.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Tropical rainforests and mangroves',
                'diet' => 'Fruits, leaves, insects, small vertebrates',
                'estimated_population' => 15000,
                'regions' => [11],
            ],
            [
                'name' => 'Kloss\'s Gibbon',
                'scientific_name' => 'Hylobates klossii',
                'common_name' => 'Gibbon',
                'description' => 'Smallest gibbon species, endemic to Mentawai Islands. Critically endangered.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Dense tropical rainforests',
                'diet' => 'Fruits, leaves, insects',
                'estimated_population' => 3500,
                'regions' => [11],
            ],
            [
                'name' => 'Mentawai Flying Lemur',
                'scientific_name' => 'Cynocephalus variegatus',
                'common_name' => 'Flying Lemur',
                'description' => 'Nocturnal gliding mammal endemic to Mentawai Islands.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Primary and secondary forests',
                'diet' => 'Leaves, fruits, insects',
                'estimated_population' => 5000,
                'regions' => [11],
            ],

            // Sulu Islands - Marine species
            [
                'name' => 'Sulu Spotted Eagle-Ray',
                'scientific_name' => 'Aetobatus narinari',
                'common_name' => 'Eagle Ray',
                'description' => 'Large marine ray found in tropical Sulu waters with distinctive white spots.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Coastal waters and coral reefs',
                'diet' => 'Fish, crustaceans, mollusks',
                'estimated_population' => 50000,
                'regions' => [10],
            ],
            [
                'name' => 'Sulu Flying Fish',
                'scientific_name' => 'Exocoetus volitans',
                'common_name' => 'Flying Fish',
                'description' => 'Fish that can glide above water surface, found in Sulu seas.',
                'species_type_id' => $fishType->id,
                'conservation_status_id' => $extinct->id,
                'habitat' => 'Open pelagic waters',
                'diet' => 'Plankton, small fish larvae',
                'estimated_population' => 1000000,
                'regions' => [10],
            ],

            // Riau Islands - Marine biodiversity
            [
                'name' => 'Horseshoe Crab',
                'scientific_name' => 'Carcinoscorpius rotundicauda',
                'common_name' => 'Horseshoe Crab',
                'description' => 'Living fossil found in Riau Islands\' mudflats and shallow waters.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Coastal mudflats and shallow waters',
                'diet' => 'Mollusks, worms, detritus',
                'estimated_population' => 50000,
                'regions' => [12],
            ],
            [
                'name' => 'Riau Clownfish',
                'scientific_name' => 'Amphiprion ocellaris',
                'common_name' => 'Clownfish',
                'description' => 'Orange and white symbiotic fish living in sea anemones in Riau coral reefs.',
                'species_type_id' => $fishType->id,
                'conservation_status_id' => $extinct->id,
                'habitat' => 'Coral reefs and anemones',
                'diet' => 'Zooplankton, small crustaceans',
                'estimated_population' => 500000,
                'regions' => [12],
            ],

            // Banda Islands - Marine and endemic species
            [
                'name' => 'Banda Sea Turtle',
                'scientific_name' => 'Chelonia mydas',
                'common_name' => 'Sea Turtle',
                'description' => 'Green sea turtle nesting beaches of Banda Islands.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Ocean and sandy beaches',
                'diet' => 'Seagrass, jellyfish, sponges',
                'estimated_population' => 100000,
                'regions' => [13],
            ],
            [
                'name' => 'Banda Endemics Frog',
                'scientific_name' => 'Dendrobates reticulatus',
                'common_name' => 'Poison Dart Frog',
                'description' => 'Brightly colored amphibian endemic to Banda Islands.',
                'species_type_id' => $amphibianType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Rainforest floor and vegetation',
                'diet' => 'Small insects and arthropods',
                'estimated_population' => 8000,
                'regions' => [13],
            ],

            // Seram Island - Tropical rainforest species
            [
                'name' => 'Seram Lory',
                'scientific_name' => 'Lorius lory',
                'common_name' => 'Lory',
                'description' => 'Beautiful red and green parrot endemic to Seram Island.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Tropical rainforests',
                'diet' => 'Seeds, nuts, fruits, nectar',
                'estimated_population' => 20000,
                'regions' => [14],
            ],
            [
                'name' => 'Seram Monitor Lizard',
                'scientific_name' => 'Varanus caerumilineatus',
                'common_name' => 'Monitor Lizard',
                'description' => 'Large tree-dwelling monitor endemic to Seram rainforests.',
                'species_type_id' => $reptileType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Rainforest canopy',
                'diet' => 'Small vertebrates, eggs, insects',
                'estimated_population' => 15000,
                'regions' => [14],
            ],

            // Halmahera - Birdlife hotspot
            [
                'name' => 'Halmahera Cockatoo',
                'scientific_name' => 'Cacatua alba',
                'common_name' => 'Cockatoo',
                'description' => 'Majestic white cockatoo endemic to Halmahera and nearby islands.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $endangered->id,
                'habitat' => 'Forests and open woodlands',
                'diet' => 'Seeds, nuts, fruits',
                'estimated_population' => 15000,
                'regions' => [15],
            ],
            [
                'name' => 'Halmahera Eagle-Owl',
                'scientific_name' => 'Buffy Fish Owl',
                'common_name' => 'Eagle Owl',
                'description' => 'Endemic nocturnal owl species from Halmahera forests.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Primary and secondary forests',
                'diet' => 'Fish, frogs, small vertebrates',
                'estimated_population' => 5000,
                'regions' => [15],
            ],

            // Morotai - Northern endemic species
            [
                'name' => 'Morotai Kingfisher',
                'scientific_name' => 'Alcedo quadribrachys',
                'common_name' => 'Kingfisher',
                'description' => 'Endemic kingfisher species found only in Morotai island.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Riverine forests and streams',
                'diet' => 'Fish, aquatic insects',
                'estimated_population' => 3000,
                'regions' => [16],
            ],

            // Ternate & Tidore - Volcanic island fauna
            [
                'name' => 'Wilson\'s Bird of Paradise',
                'scientific_name' => 'Cicinnurus respublica',
                'common_name' => 'Bird of Paradise',
                'description' => 'Stunning endemic bird with complex courtship display found in Ternate & Tidore.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Rainforest canopy',
                'diet' => 'Fruits, insects, small vertebrates',
                'estimated_population' => 8000,
                'regions' => [17],
            ],
            [
                'name' => 'Ternate Cuscus',
                'scientific_name' => 'Phalanger ursinus',
                'common_name' => 'Tree Kangaroo',
                'description' => 'Arboreal marsupial endemic to Ternate and Tidore islands.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Rainforest canopy',
                'diet' => 'Leaves, fruits, bark',
                'estimated_population' => 10000,
                'regions' => [17],
            ],

            // Alor Islands - Mixed marine-terrestrial species
            [
                'name' => 'Alor Parrot',
                'scientific_name' => 'Pseudeos fuscata',
                'common_name' => 'Parrot',
                'description' => 'Endemic parrot species from Alor Islands.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Tropical dry forests',
                'diet' => 'Seeds, nuts, fruits, insects',
                'estimated_population' => 5000,
                'regions' => [18],
            ],
            [
                'name' => 'Alor Sea Dragon',
                'scientific_name' => 'Phycodurus eques',
                'common_name' => 'Sea Dragon',
                'description' => 'Enigmatic seahorse relative found in Alor seas.',
                'species_type_id' => $marineType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Seagrass beds and kelp forests',
                'diet' => 'Small crustaceans, plankton',
                'estimated_population' => 8000,
                'regions' => [18],
            ],

            // Komodo specific
            [
                'name' => 'Komodo Boar',
                'scientific_name' => 'Sus scrofa vitatus',
                'common_name' => 'Wild Boar',
                'description' => 'Primary prey species for Komodo dragons on Komodo and Rinca islands.',
                'species_type_id' => $mammalType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Dry forests and grasslands',
                'diet' => 'Vegetation, roots, carrion',
                'estimated_population' => 3000,
                'regions' => [19],
            ],
            [
                'name' => 'Komodo Eagle',
                'scientific_name' => 'Polemaetus guineensis',
                'common_name' => 'Martial Eagle',
                'description' => 'Large predatory eagle found in Komodo\'s skies.',
                'species_type_id' => $birdType->id,
                'conservation_status_id' => $vulnerable->id,
                'habitat' => 'Open grasslands and forests',
                'diet' => 'Small mammals, birds, reptiles',
                'estimated_population' => 2000,
                'regions' => [19],
            ],
        ];

        foreach ($animals as $animal) {
            $regions = $animal['regions'];
            unset($animal['regions']);
            
            $animalModel = Animal::create($animal);
            $animalModel->regions()->attach($regions);
        }
    }
}
